### ISSUE TITLE
[Bug]Daemon长时间运行报错

### ISSUE THREAD

**Issue by Zxilly** [ZeroDream-CN/PHPMC7#5]
```
Active code page: 65001
[22:54:21 INFO] PHPMC 7 Minecraft Server Manager
[22:54:21 INFO] CopyRight (C) 2012-2018 ZeroDream.NET All Right Reserved.
[22:54:21 INFO] Server is running on port: 21567
[16:30:08 SERVER/ERROR] Exception caught, closing session
java.io.IOException: è¿œç¨‹ä¸»æœºå¼ºè¿«å…³é—­äº†ä¸€ä¸ªçŽ°æœ‰çš„è¿žæŽ¥ã€‚
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at org.apache.mina.transport.socket.nio.NioProcessor.read(NioProcessor.j
ava:317)
        at org.apache.mina.transport.socket.nio.NioProcessor.read(NioProcessor.j
ava:45)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.read(Abstract
PollingIoProcessor.java:683)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(Abstr
actPollingIoProcessor.java:659)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.process(Abstr
actPollingIoProcessor.java:648)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor.access$600(Ab
stractPollingIoProcessor.java:68)
        at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run
(AbstractPollingIoProcessor.java:1120)
        at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnabl
e.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

```

**Comment by kasuganosoras** [comment]
乱码了，有办法看到正常的报错信息嘛？
感觉这个问题应该是运行太长时间然后<s>爆栈</s>？
有待研究

**Comment by Zxilly** [comment]
乱码部分是`远程主机强迫关闭了一个现有的连接`

**Comment by kasuganosoras** [comment]
这个应该是因为不正常的 HTTP 请求造成的（例如客户端主动断开连接）
应该是因为服务端有些地方没有 Catch 到错误吧……
有空研究一下如何修复这个问题，感谢反馈。
